g<?php
/**
 * Clickable Loop Grid cards — site-wide.
 *
 * Makes every Elementor Loop Item card (`.e-loop-item`) fully clickable by
 * appending a transparent anchor overlay that covers the entire card. The
 * overlay links to the first `<a>` href found inside the card — typically the
 * post title link generated by the Loop Item template.
 *
 * This eliminates the need for visitors to click precisely on the title text
 * or a button; clicking anywhere on the card navigates to the post.
 *
 * The script runs in `wp_footer` on every front-end page. It is safe on pages
 * that contain no Loop Grid widgets because `querySelectorAll` returns an
 * empty list and the `forEach` callback never runs.
 *
 * Pages currently using Loop Grids that benefit from this:
 *  - Homepage (Hot Topics preview, Forum Categories)
 *  - Hot Topics archive (/hot-topics/)
 *  - Related Organizations (/related-orgs/ or embedded on /resources/)
 *  - Any future page that uses an Elementor Loop Grid widget
 *
 * Extracted from tiaa-elementor-forms-invite-action.php in v0.0.6 (where the
 * is_front_page() restriction was removed) and moved to this standalone file
 * in v0.0.8 as part of the plugin rename and restructure.
 *
 * @package TIAAElementor
 * @since   0.0.3
 * @updated 0.0.8 — moved to loop-grid/clickable-cards.php; logic unchanged.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'wp_footer', function () {
	?>
	<script>
        document.querySelectorAll('.e-loop-item').forEach(function(card) {
            var link = card.querySelector('a');
            if (link) {
                var url = link.href;
                card.style.position = 'relative';
                card.style.cursor = 'pointer';
                var overlay = document.createElement('a');
                overlay.href = url;
                overlay.style.cssText = 'position:absolute;inset:0;z-index:1;';
                overlay.setAttribute('aria-hidden', 'true');
                card.appendChild(overlay);
            }
        });
	</script>
	<?php
} );
